# Dockerfile.Frontend
FROM python:3.11-slim

WORKDIR /app

COPY frontend/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY frontend /app/frontend
ENV LANGSMITH_TRACING=true
ENV LANGCHAIN_TRACING_V2=true
ENV LANGSMITH_ENDPOINT="https://api.smith.langchain.com"
ENV LANGSMITH_API_KEY="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"
ENV LANGSMITH_PROJECT="ualr-chatbot"

CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
